name: saku-election-system
services:
- name: web
  source_dir: saku-strategy/backend
  github:
    repo: YOUR_USERNAME/saku-election-system
    branch: main
    deploy_on_push: true
  run_command: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
    value: your-production-secret-key
  - key: DEBUG
    scope: RUN_TIME
    type: SECRET
    value: "False"
  - key: ALLOWED_HOSTS
    scope: RUN_TIME
    type: SECRET
    value: "*.ondigitalocean.app"
  - key: ADMIN_PHONE_NUMBER
    scope: RUN_TIME
    type: SECRET
    value: "+254769582779"
