# Generated by Django 4.2.24 on 2025-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_faculty_course_code_userprofile_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ASPIRANT', 'Council Aspirant'), ('DELEGATE', 'Delegate'), ('IECK', 'IECK Member'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
