# Generated by Django 4.2.24 on 2025-11-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('CHAIR', 'Chair (President)'), ('VICE_CHAIR', 'Vice Chair'), ('SECRETARY_GENERAL', 'Secretary General'), ('FINANCE_SECRETARY', 'Finance Secretary'), ('ACADEMIC_SECRETARY', 'Academic Secretary'), ('SPORTS_SECRETARY', 'Sports Secretary'), ('SPECIAL_INTERESTS_SECRETARY', 'Special Interests Secretary')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='elections.userprofile')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='elections.userprofile')),
            ],
            options={
                'ordering': ['-voted_at'],
                'indexes': [models.Index(fields=['voter', 'position'], name='elections_v_voter_i_16ddd8_idx'), models.Index(fields=['candidate', 'position'], name='elections_v_candida_d828f9_idx')],
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
