# Generated by Django 4.2.24 on 2025-11-25 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delegate_approved_at',
            field=models.DateTimeField(blank=True, help_text='When delegate status was approved', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delegate_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_delegates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_delegate',
            field=models.BooleanField(default=False, help_text='Whether this aspirant is a delegate (votable)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed OTP attempts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Current OTP code', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='OTP expiration time', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, help_text='Lock account until this time after too many failed attempts', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last OTP sent timestamp', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='receipt',
            field=models.CharField(blank=True, help_text='Unique vote receipt number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(blank=True, help_text='Hash for vote integrity verification', max_length=64, null=True),
        ),
    ]
