name: Deploy SAKU Election System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd saku-strategy/backend
        pip install -r ../../requirements.txt
    
    - name: Run tests
      run: |
        cd saku-strategy/backend
        python manage.py test
    
    - name: Collect static files
      run: |
        cd saku-strategy/backend
        python manage.py collectstatic --noinput
    
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment triggered by push to main branch"
        echo "Render will automatically deploy this commit"